### ISSUE TITLE
Can't enable the extension

### ISSUE THREAD

**Issue by grgeorgiev** [innovationOUtside/nb_extension_wordexport#4]
OS: Win 10

After trying : jupyter bundlerextension enable --py wordexport.wordexport --sys-prefix
I got : 
Traceback (most recent call last):
  File "C:\Users\ggeorgiev\Anaconda2\Scripts\jupyter-bundlerextension-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\ggeorgiev\Anaconda2\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\ggeorgiev\Anaconda2\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\ggeorgiev\Anaconda2\lib\site-packages\notebook\bundler\bundlerextensions.py", line 297, in start
    super(BundlerExtensionApp, self).start()
  File "C:\Users\ggeorgiev\Anaconda2\lib\site-packages\jupyter_core\application.py", line 255, in start
    self.subapp.start()
  File "C:\Users\ggeorgiev\Anaconda2\lib\site-packages\notebook\bundler\bundlerextensions.py", line 211, in start
    self.toggle_bundler_python(self.extra_args[0])
  File "C:\Users\ggeorgiev\Anaconda2\lib\site-packages\notebook\bundler\bundlerextensions.py", line 203, in toggle_bundler_python
    logger=self.log)
  File "C:\Users\ggeorgiev\Anaconda2\lib\site-packages\notebook\bundler\bundlerextensions.py", line 149, in enable_bundler_python
    logger=logger)
  File "C:\Users\ggeorgiev\Anaconda2\lib\site-packages\notebook\bundler\bundlerextensions.py", line 120, in _set_bundler_state_python
    m, bundlers = _get_bundler_metadata(module)
  File "C:\Users\ggeorgiev\Anaconda2\lib\site-packages\notebook\bundler\bundlerextensions.py", line 35, in _get_bundler_metadata
    m = import_item(module)
  File "C:\Users\ggeorgiev\Anaconda2\lib\site-packages\traitlets\utils\importstring.py", line 34, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named wordexport

**Comment by psychemedia** [comment]
Did you install the package first? (You need to use the correct pip... i.e. the one that installs to the Python environment you use to run the `jupyter` command.

`pip install --upgrade --no-deps git+https://github.com/innovationOUtside/nb_extension_wordexport.git`

**Comment by grgeorgiev** [comment]
Yes,  I did that first.

**Comment by psychemedia** [comment]
Try installing with `--user` rather than `--sys-prefix`:

`jupyter bundlerextension enable --py wordexport.wordexport --user`

This extension was also created a long time ago...

A better bet may be [jupyter-docx-bundler]( https://github.com/m-rossi/jupyter-docx-bundler) although it's been some time since I last tested it (looks like it's maintained though...)
